# Generated by Django 6.0.5 on 2026-06-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_notice_student_attendance_prediction_student_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(default='eduadmin@upi', max_length=120)),
                ('transaction_ref', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.CharField(blank=True, max_length=150)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.feerecord')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
