# Generated by Django 6.0.5 on 2026-06-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('internal', 'Internal Assessment'), ('practical', 'Practical Exam'), ('entrance', 'Entrance Exam')], default='midterm', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('duration_mins', models.PositiveIntegerField(default=180, help_text='Duration in minutes')),
                ('apply_start', models.DateField()),
                ('apply_end', models.DateField()),
                ('exam_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('fee_required', models.BooleanField(default=True)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Applications Open'), ('closed', 'Applications Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.department')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hall_ticket_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to='students.student')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
