# Generated by Django 6.0.5 on 2026-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_hostelroom_roomallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('fee_due', 'Fee Due Alert'), ('fee_paid', 'Fee Payment Confirmed'), ('assignment', 'Assignment Deadline'), ('attendance', 'Attendance Warning'), ('result', 'Result Published'), ('exam', 'Exam Notification'), ('transport', 'Transport Alert'), ('announcement', 'General Announcement'), ('system', 'System')], default='announcement', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
