# Generated by Django 6.0.5 on 2026-06-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_notification_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('washing', 'Washing'), ('drying', 'Drying'), ('ironing', 'Ironing'), ('folding', 'Folding'), ('bedding', 'Bed & Pillow'), ('towels', 'Towels & Cleaning'), ('special', 'Special Care')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='per piece', help_text='e.g. per piece, per kg, per pair', max_length=30)),
                ('turnaround_hrs', models.PositiveIntegerField(default=24, help_text='Estimated delivery in hours')),
                ('is_available', models.BooleanField(default=True)),
                ('emoji', models.CharField(default='👕', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('collected', 'Collected from Room'), ('processing', 'In Process'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=30)),
                ('special_instructions', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to='students.student')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.laundryorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.laundryservice')),
            ],
        ),
    ]
