# Generated by Django 6.0.5 on 2026-06-04 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_laundry_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('upi', 'UPI'), ('razorpay', 'Razorpay'), ('qr_code', 'QR Code'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
