# Generated by Django 6.0.5 on 2026-06-04 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_hostelroom_roomallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(help_text='Unique route identifier (e.g., RT-001)', max_length=20, unique=True)),
                ('route_name', models.CharField(help_text='Descriptive name for the route', max_length=150)),
                ('start_point', models.CharField(help_text='Starting location', max_length=200)),
                ('end_point', models.CharField(help_text='Final destination', max_length=200)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Total distance in KM', max_digits=6)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in minutes')),
                ('departure_time', models.TimeField(help_text='Departure time from start point')),
                ('return_time', models.TimeField(help_text='Return time from end point')),
                ('stops_list', models.TextField(help_text='List of stops (one per line)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bus Routes',
                'ordering': ['route_number'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(help_text='Unique driver ID', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle'), ('MCWG', 'Motor Cycle With Gear')], default='HMV', max_length=10)),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='transport/drivers/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.busroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='Registration number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('minibus', 'Mini Bus')], default='bus', max_length=20)),
                ('make_model', models.CharField(help_text='Make and Model (e.g., Tata Starbus)', max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('seating_capacity', models.PositiveIntegerField(default=40)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('engine_number', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20)),
                ('mileage', models.DecimalField(decimal_places=2, default=0.0, help_text='Mileage in km/l', max_digits=6)),
                ('registration_date', models.DateField()),
                ('registration_expiry', models.DateField()),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('fitness_certificate_number', models.CharField(blank=True, max_length=50)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('breakdown', 'Breakdown')], default='active', max_length=20)),
                ('gps_enabled', models.BooleanField(default=False)),
                ('gps_device_id', models.CharField(blank=True, max_length=50)),
                ('last_gps_update', models.DateTimeField(blank=True, null=True)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Current odometer reading in KM')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='transport/vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.driver')),
                ('current_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.busroute')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('oil_change', 'Oil Change'), ('tire_change', 'Tire Change'), ('break_check', 'Brake Check'), ('engine', 'Engine Work'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('mechanic_name', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Total transport fee', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount if any', max_digits=10)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-25)', max_length=20)),
                ('semester', models.CharField(choices=[('fall', 'Fall Semester'), ('spring', 'Spring Semester'), ('annual', 'Annual')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('partial', 'Partial')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='transport.busroute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees', to='students.student')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
                'unique_together': {('student', 'route', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='DailyTripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('starting_odometer', models.PositiveIntegerField()),
                ('ending_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='transport.busroute')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='transport.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-trip_date', '-departure_time'],
                'unique_together': {('route', 'vehicle', 'trip_date', 'departure_time')},
            },
        ),
    ]
